language: python
os: linux
dist: jammy
arch: ppc64le
python: 3.11

notifications:
  email: false

addons:
  apt:
    packages:
      - libopenblas-dev

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/hdf5
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    - HDF5_CACHE_DIR=$HOME/.cache/hdf5
    - TERM=dumb
    - TOXENV=py311-test-deps
    - HDF5_VERSION=1.10.6
    - HDF5_DIR=$HDF5_CACHE_DIR/$HDF5_VERSION
    - H5PY_ENFORCE_COVERAGE=yes

before_install:
  # - export PATH=/usr/lib/ccache:$PATH
  - ccache -s

install:
    - pip install -U pip tox codecov virtualenv
    - ci/get_hdf5_if_needed.sh

script:
    - tox legacy -v $TOX_OPTS 2>&1
    - sleep 5

after_success:
    - python ci/upload_coverage.py

deploy:
  # Upload to GitHub releases on tag. Token is in secret environment vars in
  # Travis settings.
  provider: releases
  file: wheelhouse/h5py-*.whl
  file_glob: true
  edge: true # opt in to dpl v2
  on:
    tags: true
